### ISSUE TITLE
Black Magic Prove 2.1 for debugging Pixhawk(HITL Mode)

### ISSUE THREAD

**Issue by jeehopark** [PX4/PX4-Devguide#1007]
Hope all of you are doing well!
I've bought Black magic probe, tested several times and checked that chips worked okay. 
However, I couldn't find out how to use it as a debugger for HITL mode (pixhawk 4 PX1.9.0 stable)
Regardless of connection procedure, when I run it, the connection between gazebo and PX4 broke and I couldn't debug.
Is there any special way to use the Black magic probe as a debugger for HITL or it's not supposed to use for the HITL mode?
Please help me out~!

**Comment by hamishwillee** [comment]
This is for bugs in the docs, not support. The right place to post this is here: https://discuss.px4.io/c/software-development/13

When you do that, can you please state which flight controller you are using, which gazebo simulation - e.g. how are you starting it? Which OS development platform?

Also, you might want to reproduce on v1.10 or master.
