### ISSUE TITLE
HITL support for HexRotor

### ISSUE THREAD

**Issue by dustycodes** [PX4/PX4-Devguide#1023]
Hey,

Is there is any discussion or development going on to support a HITL version of the hexrotor? I have not found any yet. If not, I would like to request this as a feature to develop for the Gazebo simulation framework.

Thanks,
Dusty

**Comment by hamishwillee** [comment]
Hi @dustycodes 

Not that I know of, but this is area to discuss bugs in documentation, not in PX4 itself.

Best thing to do is post this query in https://discuss.px4.io/c/px4/25 . 

IMO if work is not underway for this, then IMO it is more likely that you'll get support to do it yourself than that the core dev team will take it on. It's not that they wouldn't want to do this, but that there are many other things they are working on.

Cheers
Hamish
