### ISSUE TITLE
Full mission example has wrong home reference frame

### ISSUE THREAD

**Issue by majassow** [PX4/PX4-Devguide#104]
[Note: this is my first post in github... please let me know (gently) all the things I did wrong so I can make sure to not repeat them.]

in dronekit-example.md, the home position is set using the global frame:
`home = vehicle.location.global_frame`
however, the Mavlink commands are using the global relative frame:
`# takeoff to 10 meters
wp = get_location_offset_meters(home, 0, 0, 10);
cmd = Command(0,0,0, mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT, mavutil.mavlink.MAV_CMD_NAV_TAKEOFF, 0, 1, 0, 0, 0, 0, wp.lat, wp.lon, wp.alt)`

The code as is causes the UAV to climb to your current home MSL + 10 meters.
Changing the home to:
`home = vehicle.location.global_relative_frame`
...causes the UAV to behave as expected.

**Comment by hamishwillee** [comment]
You're absolutely right @majassow - thanks. This is fixed by as part of #193.
