### ISSUE TITLE
Ubuntu 16.04 no longer supported?

### ISSUE THREAD

**Issue by avionicsanonymous** [PX4/PX4-Devguide#1066]
The [linux dev environment page](https://dev.px4.io/v1.9.0/en/setup/dev_env_linux.html) says 16.04 is the primary supported Ubuntu version, but the Firmware ubuntu.sh setup script flags 16.04 as unsupported, only allowing 18.04 or 20.04.

I setup my environment before this change to the startup script and only realized this when I couldn't install a later astyle version to match the Firmware CI.

**Comment by hamishwillee** [comment]
@avionicsanonymous If you read those docs you point you - for version 1.9 - you will note that they do not point to ubuntu.sh setup script. The docs for a particular version (are supposed to) work with versioned setup scripts, so if you follow the instructions on Ubuntu 16.04 they will work.

So for example if you look at the v1.10 docs you will see they do point to ubuntu.sh, but this a version that is in the 1.10 tree and was tested on both Ubuntu 18.04 an dubuntu 16.04: https://dev.px4.io/v1.10/en/setup/dev_env_linux_ubuntu.html

I think ubuntu 16 support dropped in PX4 1.11 (in beta)
