### ISSUE TITLE
Doc Bug: Flight Controller Porting Guide · PX4 v1.9.0 Developer Guide

### ISSUE THREAD

**Issue by alexmarshall132** [PX4/PX4-Devguide#1069]
NuttX porting guide has been moved from here:

http://www.nuttx.org/Documentation/NuttxPortingGuide.html

... to here ... :

https://cwiki.apache.org/confluence/display/NUTTX/Porting+Guide

Bug Page: [Flight Controller Porting Guide · PX4 v1.9.0 Developer Guide](https://dev.px4.io/v1.9.0/en/hardware/porting_guide.html)

**Comment by hamishwillee** [comment]
Thanks. This is already correct in master, and generally I don't back-port fixes to older versions: https://dev.px4.io/master/en/hardware/porting_guide_nuttx.html

That said, I did this in this case, so I can show you the easy way to make these changes yourself if you want.

Firstly, check the link is not incorrect in master. Fixing it in master is the right thing to do as it will go into future versions. 
At the top of every page is this link
![image](https://user-images.githubusercontent.com/5368500/89493361-57505d80-d7f7-11ea-8d85-9333f2b95412.png)

If you click it this will open the master version of the doc for editing. E.g. in this case https://github.com/PX4/Devguide/blob/master/en/hardware/porting_guide.md

Fix. Submit PR. Done.

For an older version, e.g. 1.9 ... do the same thing, but change the URL in the page that opens to the correct branch name - e.g. https://github.com/PX4/Devguide/blob/v1.9.0/en/hardware/porting_guide.md

Fix, Submit PR. Done.

Hope that makes sense.
