### ISSUE TITLE
running offb_node.cpp

### ISSUE THREAD

**Issue by Iko-Git** [PX4/PX4-Devguide#1120]
Hello, 
Could you please guide me how to run offb_node.cpp
.....
Please take it into consideration that I installed PX4 using following the below instructions:
Download PX4 Source Code:
-git clone https://github.com/PX4/PX4-Autopilot.git --recursive
Run the ubuntu.sh with no arguments (in a bash shell) to install everything:
-bash ./Tools/setup/ubuntu.sh

**Comment by RicardoM17** [comment]
Hi @Iko-Git have you looked into https://dev.px4.io/master/en/ros/mavros_offboard.html ?

In a nutshell you need to add the file to your ROS package, build it, then launch a gazebo simulation, launch mavros via roslaunch (check the page after the one I sent) and then run the offbnode via rosrun.

**Comment by hamishwillee** [comment]
@Iko-Git Best place to ask support questions is https://discuss.px4.io/ . This area is where you post questions about specific issues with the documentation. I am therefore closing.

**Comment by Iko-Git** [comment]
Thanks got solved!
@hamishwillee 
@RicardoM17

**Comment by RicardoM17** [comment]
Glad to hear it @Iko-Git 

Best of luck and have fun developing :)
