### ISSUE TITLE
Link refers to the wrong place. 

### ISSUE THREAD

**Issue by roman-dvorak** [PX4/PX4-Devguide#1143]
Link in the alert box (about merging dev and docs docs) on [Introduction page](https://dev.px4.io/master/en/index.html) refers to the wrong place `http://localhost:8080/px4_user_guide/en/development/development.html`

![obrazek](https://user-images.githubusercontent.com/5196729/103460929-c1275180-4d1a-11eb-9d03-beb0f86c270d.png)

**Comment by hamishwillee** [comment]
Thanks. Fixed.
