### ISSUE TITLE
Doc Bug: TBS Caipiroshka · PX4 Developer Guide

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-Devguide#138]
There is a missing zip file "design files" on this page - 

```
* Left and right 3D-printed motor mount ([design files](parts/motor_mounts.zip))
```

Any idea where they might be located?

Bug Page: [TBS Caipiroshka · PX4 Developer Guide](https://dev.px4.io/en/airframes_vtol/caipiroshka.html)

**Comment by hamishwillee** [comment]
@bkueng Any ideas?

**Comment by mhkabir** [comment]
@tumbili Should have it.

**Comment by hamishwillee** [comment]
@tumbili Roman, any idea where we can get those files?

**Comment by RomanBapst** [comment]
@hamishwillee Hi! Let me check on my old laptop, it could be that I have them there. Otherwise @LorenzMeier could still have them.

**Comment by hamishwillee** [comment]
Thanks, any luck @tumbili ?

**Comment by RomanBapst** [comment]
@hamishwillee Just sent them to you via Slack.

**Comment by hamishwillee** [comment]
Thank you @tumbili . All fixed now
