### ISSUE TITLE
Docker page no longer accessible

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [PX4/PX4-Devguide#167]
Since 2 days the Docker page and others from "Testing and CI" category are no longer accessible.
Check this commit:
https://github.com/PX4/Devguide/commit/5a329d12d5db2bb8e3697674fd1c06a460570a09#diff-e75fb246c17ec91f37861dccb8d751bf

**Comment by hamishwillee** [comment]
@mhkabir Hi Kabir - was the deletion shown at that link an accident?

**Comment by mhkabir** [comment]
Ugh. No idea how this happened. Looks like a Gitbook editor fail - I never intended to remove those links.

I'll re-insert them.

**Comment by mhkabir** [comment]
Fixed, thanks for letting me know.
