### ISSUE TITLE
External Position Estimation needs to be updated

### ISSUE THREAD

**Issue by oceanusxiv** [PX4/PX4-Devguide#191]
The current documentation in the DevGuide in regards to External Position Estimation is quite outdated. In particular since EKF2 is now feature complete and the default estimation engine, the guide should at least be extended to cover external position estimation under EKF2 in addition to the existing docs for LPE. 

The current documentation on ecl EKF is quite extensive and cover some of the material already.

**Comment by mhkabir** [comment]
We will update it. LPE is still the recommended estimator for motion capture and vision use-cases till we have more testing on EKF2. e.g https://github.com/PX4/Firmware/issues/7408

**Comment by bramsvs** [comment]
@mhkabir Maybe time to update this? I'm happy to help but I have to get it working first ;)

**Comment by hamishwillee** [comment]
... and probably LPE no longer the recommended estimator @mhkabir

**Comment by mhkabir** [comment]
Yeah, we have EKF2 dialed in now and should be the recommend estimator.

**Comment by hamishwillee** [comment]
Thanks @mhkabir . Can you help @bramsvs get started?

**Comment by m0oz** [comment]
Hey there. Just chiming in.

It seems like this is still relevant. I haven't contributed to the doc yet but I am about to start my implementation of external pose estimate + EKF2 and I could add my findings to
https://dev.px4.io/en/ros/external_position_estimation.html

**Regarding the overall structure of the doc on external vision:**
To me it was counter-intuitive to find the doc on external vision split between 
[Robotics/ROS/ExternalPositionEstimate](https://dev.px4.io/en/ros/external_position_estimation.html) and [Tutorials/eclEKF](https://dev.px4.io/en/tutorials/tuning_the_ecl_ekf.html)
I think https://dev.px4.io/en/tutorials would need an additional page that gives more details on how to setup your vio->mavros->px4 pipeline and how to tune ekf2 for this application.
Robotics/ROS/ExternalPositionEstimate could then just link to this tutorial as it currently reads as a tutorial anyways.

I think this supports what was mentioned here #530 @hamishwillee

**Comment by hamishwillee** [comment]
Hi @m0oz 

We definitely need clear docs on external vision. It is completely appropriate for a separate EKF tutorial, but the important aspects should either be included or strongly linked from the external position docs.
I am not sure having a separate document for vio->mavros->px4 makes sense - it probably can be merged - or the common bits should be split.

I should also add that I am trying to kill that whole section on tutorials by moving the docs into sections with associated content and making them more guide than tutorial. I don't hate tutorials, but there is a tendency for them to cover just one setup case and not have enough information for people to extend them to more general use cases. 

With respect to the ExternalPositionDoc, is any of what you're proposing covered in the updated in https://github.com/PX4/Devguide/pull/573 ?

Cheers
H 

PS I appreciate my response is a bit superficial. Once you've looked at #573 I will think about this more "completely". Your help/experience on getting the information for this updated will be invaluable.
