### ISSUE TITLE
Annoying user-facing messages during radio calibration

### ISSUE THREAD

**Issue by mhkabir** [PX4/PX4-Devguide#195]
We should get rid of these. The "disarmed" messages are misleading and annoying.

![image](https://user-images.githubusercontent.com/5557676/27295729-83bd8f06-553b-11e7-886f-f79b87d831c0.png)

**Comment by DonLakeFlyer** [comment]
QGC should put the vehicle in radio calibration mode which I thought was supposed to make these sort of checks not happen.

**Comment by mhkabir** [comment]
Looks like something's broken. Also I opened the issue in the wrong repo lol. Let me relocate.

**Comment by mhkabir** [comment]
@DonLakeFlyer continued here : https://github.com/PX4/Firmware/issues/7444
