### ISSUE TITLE
Doc Bug: Contributing & Dev Call · PX4 Developer Guide

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [PX4/PX4-Devguide#200]
Weekly Dev Call time and "location" seems to be inconsistent with respect to forum info.

Bug Page: [Contributing & Dev Call · PX4 Developer Guide](https://dev.px4.io/en/contribute/)

**Comment by hamishwillee** [comment]
Thank you @AlexandreBorowczyk - I have updated the forum as per the page above, which is correct.
