### ISSUE TITLE
Doc Bug: Motor Map · PX4 Developer Guide

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-Devguide#205]
@bkueng Do we need still [Motor Map · PX4 Developer Guide](https://dev.px4.io/en/airframes_multicopter/motor_map.html) ?

The [Airframe reference](https://dev.px4.io/en/airframes/airframe_reference.html) is far more complete and useful. We could redirect links to here to the Airframes reference instead. 

If we do keep this, we should update it to link to the Airframes ref.

**Comment by bkueng** [comment]
No I don't think we still need it. All of the information is contained in the Airframe reference.

**Comment by hamishwillee** [comment]
Great, fixed in https://github.com/PX4/Devguide/pull/207
