### ISSUE TITLE
Doc Bug: Adding a new Airframe · PX4 Developer Guide

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [PX4/PX4-Devguide#214]
Not as much as a problem but rather a suggestion.
Maybe it would be pertinent to concatenate the information found at https://dev.px4.io/en/concept/mixing.html and adding a new frame -> mixer file

Bug Page: [Adding a new Airframe · PX4 Developer Guide](https://dev.px4.io/en/airframes/adding_a_new_frame.html)

**Comment by hamishwillee** [comment]
I'm going to close this. They need to be more clearly linked (you have to read the mixing file before this makes sense) but they don't precisely join together.
