### ISSUE TITLE
link to outdated pixhawk.org parameter list

### ISSUE THREAD

**Issue by FriendlyDwarf** [PX4/PX4-Devguide#283]
Hey,

i just noticed that the link behind the SYS_COMPANION under 2. in https://dev.px4.io/en/ros/offboard_control.html links to the old parameter site https://pixhawk.org/firmware/parameters#system, which offers a link to go back to the new guide https://dev.px4.io/en/advanced/parameter_reference.html.

**Comment by hamishwillee** [comment]
Fixed. Thank you @FriendlyDwarf
