### ISSUE TITLE
Missing @class in "Adding a new Airframe Configuration"

### ISSUE THREAD

**Issue by KochC** [PX4/PX4-Devguide#306]
In the config file is the class tag missing.

```
# @type Flying Wing
```

should be something like
```
# @type Flying Wing
# @class VTOL
```

**Comment by hamishwillee** [comment]
Relevant doc is:  [Adding a new Airframe Configuration](https://dev.px4.io/en/airframes/adding_a_new_frame.html)

**Comment by hamishwillee** [comment]
Thanks very much. This is fixed by https://github.com/PX4/Devguide/pull/307
