### ISSUE TITLE
Download ubuntu_sim_nuttx.sh missing

### ISSUE THREAD

**Issue by danielesartori** [PX4/PX4-Devguide#311]
In the Toolchain Installation/Linux (https://dev.px4.io/en/setup/dev_env_linux.html), section Pixhawk/NuttX and jMAVSim/Gazebo Simulation, the link to the file ubuntu_sim_nuttx.sh is not working.
It was working 10 days ago

Thanks

**Comment by danielesartori** [comment]
I guess now the file is here

https://github.com/PX4/Devguide/tree/master/build_scripts

**Comment by hamishwillee** [comment]
Thanks very much! This was fixed by https://github.com/PX4/Devguide/pull/312 (the file hasn't moved, but the documentation was updated incorrectly in a "bulk fix" for an unrelated issue)

**Comment by hamishwillee** [comment]
(PS it will take a few minutes for the docs to rebuild)

**Comment by danielesartori** [comment]
Thank you for fixing it!

**Comment by hamishwillee** [comment]
I'd love to claim credit, but we have @ShikherVerma to thank!
