### ISSUE TITLE
Update jMAVSim docs with new screenshot

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-Devguide#330]
jMAVSim has a new look, or will when https://github.com/PX4/Firmware/pull/8194 goes in. The action is to update https://dev.px4.io/en/simulation/jmavsim.html with some better imagery. 

Take some time to improve the doc too :-)

**Comment by MaEtUgR** [comment]
@hamishwillee This issue is probably not up to date anymore?

**Comment by hamishwillee** [comment]
Thanks @MaEtUgR . Fixed way back when. Will close.
