### ISSUE TITLE
Can't change to OFFBOARD Mode in Ros Gazebo 

### ISSUE THREAD

**Issue by ghost** [PX4/PX4-Devguide#340]
Hello everyone, i really need help as i am new in Gazebo. 

i have cloned the PX4 Firmware source from https://github.com/PX4/Firmware in my home directory.
Then i go to ~/src/Firmware and type this in my terminal : 
$ make posix_sitl_default gazebo 
After the gazebo simulation and the iris model appeared, i open new terminal and run this command 
$ roslaunch px4 mavros.launch

The mavros has connected successfully to gazebo and i can change the mode using command 
$ rosservice call /mavros/set_mode "base_mode: 0
custom_mode: 'AUTO.LAND'"
and the result is like this 
![screenshot from 2017-11-06 16-09-22](https://user-images.githubusercontent.com/11459739/32433307-1a8909bc-c30d-11e7-88a9-7d3cdff9e110.png)

and then i want to change to OFFBOARD mode, and the result is like this 
![screenshot from 2017-11-06 16-13-28](https://user-images.githubusercontent.com/11459739/32433424-772608d2-c30d-11e7-99a8-63a321504670.png)

the mode_sent is true, but the mode is not changed to OFFBOARD mode. 

Is there anyone know how to change to offboard mode in gazebo ?

**Comment by TSC21** [comment]
You cannot change to offboard without first publish a stream of setpoints. That is clear on the offboard section of the devguide.

**Comment by ghost** [comment]
aaa i see i see.. that's work. Thankyou very much :)
