### ISSUE TITLE
Doc Bug: MAVROS offboard example · PX4 Developer Guide

### ISSUE THREAD

**Issue by KochC** [PX4/PX4-Devguide#367]
DESCRIBE PROBLEM WITH DOCS HERE

I get this message after running this node.
```
[ERROR] [1511449066.433408097]: MODE: Unsupported FCU
```

And I can not switch into OFFBOARD mode with my transmitter, but as far as I understand, this should not be possible?

Also the video is not working :/

Bug Page: [MAVROS offboard example · PX4 Developer Guide](https://dev.px4.io/en/ros/mavros_offboard.html)

**Comment by TSC21** [comment]
@KochC this is not a bug related to docs. Please move this issue to to appropriate bug tracking issue list on PX4 or in MAVROS - there, I ask you to please describe your setup. From your description, it's impossible for any developer to understand what is going on.
