### ISSUE TITLE
Doc Bug: Land Detector: thrust equations

### ISSUE THREAD

**Issue by ndepal** [PX4/PX4-Devguide#383]
The equations for the thrust conditions of "ground contact" and "maybe landed" don't seem to correspond to the ones in the code.

They should be:

`MPC_THR_MIN + (MPC_THR_HOVER - MPC_THR_MIN) * 0.3f`

and

`MPC_THR_MIN + (MPC_THR_HOVER - MPC_THR_MIN) * LNDMC_THR_RANGE`

respectively.

Bug Page: [Land Detector · PX4 Developer Guide](https://dev.px4.io/en/tutorials/land_detector.html)

**Comment by hamishwillee** [comment]
Thanks, I agree, based on: https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L331
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/MulticopterLandDetector.cpp#L340

This fixed in #383
