### ISSUE TITLE
Doc Bug: HITL Simulation · PX4 Developer Guide

### ISSUE THREAD

**Issue by ndepal** [PX4/PX4-Devguide#436]
Gazebo HITL is not actually supported yet. Open PR here: https://github.com/PX4/sitl_gazebo/pull/157
I just spent about an hour trying to get this working according to the docs. They should mention that this is not in master yet.

Bug Page: [HITL Simulation · PX4 Developer Guide](https://dev.px4.io/en/simulation/hitl.html#simulator-setup)

**Comment by TSC21** [comment]
Merged on `sitl_gazebo` side. TODO: add support for other airframes (on PX4 side).

**Comment by ndepal** [comment]
Thanks. It's still not available in Firmware master though.

**Comment by LorenzMeier** [comment]
@TSC21 Could you send a PR?

**Comment by TSC21** [comment]
It's already on master.

**Comment by ndepal** [comment]
I see that it was added yesterday https://github.com/PX4/Firmware/pull/8752. Thanks!

**Comment by DanielPalominoS** [comment]
Hello, I have been working with a pixhawk 2 in HITL. When I use either 1.7.x or 1.8.x firmware version sensor messages are received. However, when I use 1.9.x firmware version this is not the case, same as happened before to @arwagoner  in [PX4/sitl_gazebo#157](https://github.com/PX4/sitl_gazebo/pull/157). I wonder if  this is any issue associated with this specific board or perhaps is a general behavior in 1.9.x firmware upgrade.
Sorry if this is not the right place to post, I was not sure where to do it. 
Thank you in advance to those who could provide any help.

**Comment by TSC21** [comment]
@DanielPalominoS please bring your questions to PX4 Slack or to discuss.px4.io
