### ISSUE TITLE
Configurate PX4 SITL for AirSim

### ISSUE THREAD

**Issue by mrRedDead98** [PX4/PX4-Devguide#438]
Hey guys,

I am running AirSim and QGroundControl on Windows 10 and PX4 in VM. I am able to connect AirSim, QGC via PX4 but that's all. 

1. Which parameters do I have to set for successful preflight. For example how and where can I calibrate the sensors for my AirSim. Especially to configurate the altitude for QGC and the Errors below.

2. In the config-file for px4 I set the LPE_LAT and LPE_LON params to my local but the commander 
 overrides home parameter as you can see below but if I look up the values of my LPE params they are the same I declared in config-file. 

![capture](https://user-images.githubusercontent.com/30799998/35283972-e27e1e1a-0059-11e8-9aa7-129d94ce0aee.PNG)

My purpose is to fly in the AirSim Blocks-Simulation with the given quadrocopter-drone.
Hope someone can help me.

**Comment by hamishwillee** [comment]
Closing as this section is for defects in the documentation. If you want technical support, I suggest you start on the Airsim page https://github.com/Microsoft/AirSim/blob/master/docs/px4_setup.md
