### ISSUE TITLE
Incorrect handling of baud rate values in RTPS

### ISSUE THREAD

**Issue by drisebor** [PX4/PX4-Devguide#448]
in RTPS both client and agent code, baud rate values are generated from the program argument by converting the argument directly to a number. However in termios.h, the baud rate is encoded in a number of preset values, eg B57600. This affects the agent running on Ubuntu since the encoded value is different from the actual baud rate. As a result executing:
./micrortps_agent -b 57600 -d /dev/ttyUSB1
results in the error:
UART transport: device: /dev/ttyUSB1; baudrate: 57600; sleep: 1us; poll: 0ms

ERR SET BAUD /dev/ttyUSB1: 0 (22)
Close UART
EXITING...

**Comment by drisebor** [comment]
I've put together a fix with minimum change that's ready to go if the bug is agreed to be real.
btw. I'm new to PX4. I'm on a project that involves using RTPS to communicate with a companion computer.

**Comment by drisebor** [comment]
Sorry, I think I raised this issue in the wrong place! Somehow I followed a link to the devguide and didn't realise my newby mistake.

**Comment by hamishwillee** [comment]
Thanks!
