### ISSUE TITLE
npm install brings me " no such file or directory"

### ISSUE THREAD

**Issue by jiapei100** [PX4/PX4-Devguide#47]
> jiapei:Devguide$ npm install
> npm WARN enoent ENOENT: no such file or directory, open '....../px4/Devguide/package.json'
> npm WARN Devguide No description
> npm WARN Devguide No repository field.
> npm WARN Devguide No README data
> npm WARN Devguide No license field.

cheers 
Pei

**Comment by julianoes** [comment]
I don't think this devguide brings this functionality anymore.
However, it's just a gitbook, so this might help: https://github.com/GitbookIO/gitbook-cli

**Comment by julianoes** [comment]
As said, we just use gitbook. So please look at their instructions how to locally deploy it. And if it doesn't work, ask there please. Thanks.
