### ISSUE TITLE
uORB: naming of multi-topics vs multi-instance

### ISSUE THREAD

**Issue by jlecoeur** [PX4/PX4-Devguide#477]
The [uORB dev guide](https://dev.px4.io/en/middleware/uorb.html) is a bit confusing now because it calls **instance** both 
- the multiple topic names defined with `# TOPICS` in .msg files
- the multiple topic instances advertised with `orb_advertise_multi`

The [uORB generation script](https://github.com/PX4/Firmware/blob/master/msg/tools/px_generate_uorb_topic_files.py#L92) calls the former **multi-topics**.

What is the correct naming convention?

**Comment by bkueng** [comment]
Multi-instance (or just instances) is for `orb_advertise_multi`, and usually `multi-topic` is used for multiple topic names (via `# TOPICS`).
Do you want to update the docs accordingly?

**Comment by jlecoeur** [comment]
Thanks! Here is the (tiny!) PR #478

**Comment by bkueng** [comment]
Tiny indeed! Thanks :)
