### ISSUE TITLE
(potentially) Error note

### ISSUE THREAD

**Issue by BazookaJoe1900** [PX4/PX4-Devguide#508]
@dagar 
I am not 100% sure if I am right or not but I think that there is an error here:
https://dev.px4.io/en/tutorials/tuning_the_ecl_ekf.html?q=#what-should-i-do-if-the-height-estimate-is-diverging
(I think that)  the erorr is _"ekf2_innovations.vel_pos_innov[3] and ekf2_innovations.vel_pos_innov[5] will both have the same sign."_
but vel_pos_innov[3] should be vel_pos_innov[2]. that will make more sense because [2] and [5] are both relevant to Z axis.

**Comment by hamishwillee** [comment]
@priseborough This one for you

**Comment by BazookaJoe1900** [comment]
@hamishwillee @priseborough, is my note true?
I can do the pr if it is...

**Comment by hamishwillee** [comment]
@BazookaJoe1900 I have no idea, which is why I deferred to @priseborough . Let's broaden the search - @dagar @mhkabir Do you know?

**Comment by priseborough** [comment]
Yes, should be vel_pos_innov[2]

**Comment by hamishwillee** [comment]
THanks @priseborough 

@BazookaJoe1900 Yes. adding a note as a PR would be great. Please link to here.
