### ISSUE TITLE
Should the module template be moved out of System into Template

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-Devguide#512]
The template module has docs that are auto generated [here](https://dev.px4.io/en/middleware/modules_system.html#module) (System group). 

@bkueng  Should we create a special group Template?

**Comment by bkueng** [comment]
I agree, it does not really fit. See https://github.com/PX4/Firmware/pull/9324
Can you add the required TOC?

**Comment by hamishwillee** [comment]
Thanks @bkueng - much appreciated. Added to TOC.
