### ISSUE TITLE
Doc Bug: Preflight Checks · PX4 Developer Guide: Undocumented preflight failure

### ISSUE THREAD

**Issue by ndepal** [PX4/PX4-Devguide#518]
The following preflight failure is not documented:
"PREFLIGHT FAIL: EKF INTERNAL CHECKS"
It is printed [here](https://github.com/PX4/Firmware/blob/7bc3a12efe7f95f66e968d506829f1488e63480e/src/modules/commander/PreflightCheck.cpp#L539).

Bug Page: [Preflight Checks · PX4 Developer Guide](https://dev.px4.io/en/tutorials/pre_flight_checks.html)

**Comment by hamishwillee** [comment]
Yes, already working on it in https://github.com/PX4/Devguide/pull/510

**Comment by hamishwillee** [comment]
(and noting that this will move into the PX4 User Guide)

**Comment by ndepal** [comment]
Sorry, didn't see that. That's great!

**Comment by hamishwillee** [comment]
No worries - thanks for posting - for every issue I've already got ongoing work on I'm sure there are millions of things that I missed :-)

This got merged. It is now being moved into the USER guide.
