### ISSUE TITLE
No index on dev website

### ISSUE THREAD

**Issue by TokyoClod** [PX4/PX4-Devguide#531]
Found no index or catalog on the dev site whether [https://dev.px4.io/en/](https://dev.px4.io/en/) or [https://dev.px4.io/zh/](https://dev.px4.io/zh/)

**Comment by hamishwillee** [comment]
Thanks for your comment.

You're right, we haven't chosen to add any other specific index or "catalog" (not sure what you mean by that). These sorts of things are not supported by the toolchain, and it would not be a good investment of time to create them manually.

 The content is searchable and organised in the sidebar.

I am therefore closing.
