### ISSUE TITLE
Doc Bug: jMAVSim Simulation · PX4 Developer Guide

### ISSUE THREAD

**Issue by ndepal** [PX4/PX4-Devguide#533]
The PX4_HOME_LAT, PX4_HOME_LON, and PX4_HOME_ALT environment variables can be used to configure the home position. The documentation only mentions it on the Gazebo page, but not on the jMAVSim page.

Bug Page: [jMAVSim Simulation · PX4 Developer Guide](https://dev.px4.io/en/simulation/jmavsim.html)

**Comment by hamishwillee** [comment]
Fixed by #542. Sorry for the delay. Off work.
