### ISSUE TITLE
Hint to QGC console is missing in console guide

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/PX4-Devguide#557]
@bkueng Could you do a quick pass?

https://dev.px4.io/en/debug/system_console.html

**Comment by bkueng** [comment]
First needs this: https://github.com/mavlink/qgc-user-guide/issues/143

**Comment by hamishwillee** [comment]
EDITED: Will be fixed by https://github.com/mavlink/qgc-user-guide/pull/145

**Comment by hamishwillee** [comment]
Note that this is somewhat mentioned here: https://dev.px4.io/en/debug/system_console.html#mavlink-shell

**Comment by hamishwillee** [comment]
@bkueng Here you go https://docs.qgroundcontrol.com/en/analyze_view/mavlink_console.html

**Comment by bkueng** [comment]
Thanks @hamishwillee. One note: the console can also be used via Telemetry, not only WiFi.

Devguide PR: https://github.com/PX4/Devguide/pull/560

**Comment by hamishwillee** [comment]
@bkueng Hmm, the note was supposed to indicate that the benefit is deep access while flying, not that it is restricted to wifi. I have reworded to clarify: https://github.com/mavlink/qgc-user-guide/commit/1feb42d763c578549e8e3803fd561ac7723f3615
