### ISSUE TITLE
Would be really gratefull for a pdf snapshot

### ISSUE THREAD

**Issue by antoan** [PX4/PX4-Devguide#567]
I've spent considerable about of time trying to install gitbook locally on Ubuntu 14.04 but I keep running into issues involving setting up npm, nvm.

**Comment by hamishwillee** [comment]
That is not possible. Unfortunately the system relies on some plugins that aren't compatible with PDF (mermaid). 

Can you install on Ubuntu 16.04 - that is what I use?

**Comment by woeimun** [comment]
After installing a loads of software ;nodejs,npm,gitbook,git,svgexport, and all the plugins.
I can't even convert into PDF!
I gets a few warnings on deprecated properties, than TypeError: speech.processExpression is not a function. And I got thrown out from "gitbook pdf ./ ./px4doc.pdf"
Could anyone manage to perform gitbook conversion to PDF, please help to provide a link for us to download. Thank you.

**Comment by hamishwillee** [comment]
@woeimun Didn't you read my comment above: https://github.com/PX4/Devguide/issues/567#issuecomment-408366811

Not supported. Even if we did support it, you're talking a 100Mb PDF. Unusable, unsharable.
