### ISSUE TITLE
Error in documentation for building code for snapdragon

### ISSUE THREAD

**Issue by sharvashish** [PX4/PX4-Devguide#61]
In this [link](dev.px4.io/starting-building.html)
Under Run it for Snapdragon Flight,

to launch mini-dm, the command should be:
**${HEXAGON_SDK_ROOT}/tools/debug/mini-dm/Linux_Debug/mini-dm**

instead of **${HEXAGON_SDK_ROOT}/tools/mini-dm/Linux_Debug/mini-dm**

**Comment by julianoes** [comment]
@sharvashish thanks for reporting. Fixed in #62.

**Comment by sharvashish** [comment]
Hi, guys sorry for the wrong link,
But I was trying to mention this link: [here](http://dev.px4.io/starting-building.html#run-it)

Even though raising this issue corrected the same error in few other places, the error is repeated here as well. Please correct it here too. 

Cheers.

**Comment by julianoes** [comment]
@sharvashish oh yes there as yet another one, thanks.
Fixed in #63.
