### ISSUE TITLE
Request: Add Bulgarian language Localization.

### ISSUE THREAD

**Issue by tubeme** [PX4/PX4-Devguide#620]
Hi guys,

@hamishwillee @dagar  Can somebody add a Bulgarian language localization to the crowd.in so I could start the translation?

Thanks in advance.

**Comment by hamishwillee** [comment]
I've added Bulgarian for the devguide, and in case you're feeling particularly motivated, also for QGroundControl (app). Thanks!!!!

**Comment by hamishwillee** [comment]
PS Bulgarian invite link once you have a crowdin account is [here](https://crowdin.com/project/px4-developer-guide/invite?d=d5a5o4755507930733j4n4h38363) - to devguide. I can add one for QGC when you are ready.

**Comment by tubeme** [comment]
Actually I want to start with the QGC app and then move to the Users Manual so to include proper screenshots.

Thanks @hamishwillee
