### ISSUE TITLE
Add docs for posix dynamic modules on Posix + FIFOs

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-Devguide#656]
Support for dynamic modules on Posix (and possibly nuttx, untested) added in https://github.com/PX4/Firmware/pull/10870#issuecomment-439932956

Needs to state what it can be used for and how it is used.
* [ ] Possibly add a section in  [System Startup](http://dev.px4.io/en/concept/system_startup.html) linked from a small note in the [app tutorial](http://dev.px4.io/en/apps/hello_sky.html).

* [x] In addition, the section in [System Startup](http://dev.px4.io/en/concept/system_startup.html) about client/daemon FIFOs is no longer true. 

Hoping that @m-ou-se will create PR :-)

**Comment by m-ou-se** [comment]
Updated documentation on the client/daemon communication in #662.

Will submit a PR for the dynamic modules as soon as https://github.com/PX4/Firmware/pull/10870 is merged.

**Comment by m-ou-se** [comment]
The code is merged. #663 updates the documentation.
