### ISSUE TITLE
PX4 fmu_v6

### ISSUE THREAD

**Issue by alexcherpi** [PX4/PX4-Devguide#675]
Hi,

I've seen that the fmu_v6 with the STM32H7 is [in progress](https://github.com/PX4/Devguide/blob/master/en/debug/reference-design.md).
- When are you going to release a working version of the fmu_v6 ? 
- Are you using a STM32H7 with an internal flash ?

Thanks, 
Alex

**Comment by hamishwillee** [comment]
@alexcherpi Probably best to ask this on the [forums](http://dev.px4.io/en/#support). It isn't a bug in the docs, which is what this area is for. Yes, good to link to the doc in question when you do so: http://dev.px4.io/en/debug/reference-design.html#reference_design_generations
