### ISSUE TITLE
New infrastructure to support versioned docs builds (Dev/User guide)

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-Devguide#676]
Dev and User guide reflect state of "master" but many users are working on the latest stable version (or older versions). This results in confusion when new features or changes are added to the docs. The problems increase as the master branch diverges. 

This is difficult to manage by adding notes in master - we don't always know what releases things will go into, and we don't want to have both new and old instructions in the docs, and have to remember where things changed. 

The best solution is to spawn off a separate doc set for each new version. We have a plugin already in place to support this, but we will need to update our Jenkins and URLs to enable it.

The desired solution
- [ ] Devguide github branches built to `https://dev.px4.io/<branch_name>/* ` (for all branches)
  - Docs match branches - created, updated, and deleted based on what happens in github
  - Current docset effectively moved to `https://dev.px4.io/master/*`
- [ ]  Redirect current URLs:
  - [ ] https://dev.px4.io/ TO https://dev.px4.io/master/ (ie root URL)
  - [ ] https://dev.px4.io/en/* TO https://dev.px4.io/master/en/*
  - All other paths unchanged - no need to redirect the /zh, /kr paths.
 - [ ] Docs for User Guide exactly the same approach as above (but obviously with different root)

An less-desired alternative is to use tags for building non-master-branch docs. This would be same, except obviously a tag can be created or deleted, but not updated.

**Comment by bys1123** [comment]
![image](https://user-images.githubusercontent.com/4748411/50525789-a5c85100-0b18-11e9-9c6f-9be0f3158fde.png)
I'm developing a website compatible with gitbook, make sure chinese developer can switch versions at mirror site in china, and make translation update easier.
https://github.com/DimianZhan/ThiOne
It's based on Laravel, a very powerful php framework, getting popular in recent years, easy to add new features. It's not fully functional yet, will be ready in two weeks.

**Comment by hamishwillee** [comment]
@bys1123 That looks pretty nice. Gitbook actually has a solution for versions which you can see in action here: https://sdk.dronecode.org/en/
We plan to turn this on in the coming days (ie close this issue). 

It is good to know that there are other compatible solutions out there for markdown. I wouldn't probably switch to another system without a compelling reason (which version support is not, given that we just need to enable it). I'm also a big fan of truly static sites because it makes hosting easier and cheaper to setup and maintain than one which requires a programming environment. 

A compelling reason to update to a system with some sort of backend would be a fantastic collaborative editing experience. Gitbook are trying to achieve this but are still some way from achieving it.

**Comment by bys1123** [comment]
@hamishwillee Understand. I'll also try to make it better, looks hard, but programming is fun.

The reason I did not still use gitbook, because of the version plugin only support the "branch" method when you use gitbook.com. If use manual configuration, experience is not that good.

https://plugins.gitbook.com/plugin/versions

That will need edit the books.json in each version, also static pages is in _book folder in each version, need to config the url rewrite in Nginx or Apache.

**Comment by hamishwillee** [comment]
Hi @bys1123 
The branch method is actually better for docs (usually) because there is often a need to go back and tidy mismatches in the old docs. For example, if I take a snapshot of docs right now it includes some stuff that will not be in the next release. 

> That will need edit the books.json in each version, also static pages is in _book folder in each version, need to config the url rewrite in Nginx or Apache.

Incorrect. The selector for all builds is picked up dynamically from what you put in `gitbookConfigURL` - so whatever you have in book.json for your mappings is used for your old static builds too. No url re-writes or whatever. 
The only complication we will have (which Daniel is resolving) is the redirect from the root dev.px4.io to our default build. 

We will generate separate trees for each version to match branches in github.

To be clear, I think what you're doing is cool. If we got to the point where a dynamic build was no longer possible we might even consider moving to it :-)

**Comment by bys1123** [comment]
@hamishwillee Thanks for your explain. But my point is lot's of developer in china can't comfortablely visit gitbook.com service that hosting Docs of Dronecode, it's very slow because of GFW. If it's good, we don't even need to use a mirror site in china.
That's why we(the mirror site) can't use the branch method, I know it's very easy way.

> Incorrect. The selector for all builds is picked up dynamically from what you put in gitbookConfigURL

The examples is using github.io service, so it will redirect to correct root directory automatically. If use Nginx, It will need to manual config the re-writes.

I'm not trying to convince you use this project, I'm tring to provide better service to Chinese developers, make them easier to join in global community someday.

**Comment by hamishwillee** [comment]
@bys1123 that is a good argument for hosting in China, but it is not a good technical argument for using a custom toolchain - there is nothing to stop you using what we publish out of the box hosted on your side of the GFW.

FYI, we are using branches for releases (you can see v1.8.0 and v1.8.2 have now appeared in github). The version support should all be rolled out this week. 

So I see the new generator as cool but unnecessary work "right now".

SHould I close this?

**Comment by bys1123** [comment]
I didn't see this project before, https://github.com/PX4/dev.px4.io , this fixed my problem.

**Comment by hamishwillee** [comment]
> I didn't see this project before, https://github.com/PX4/dev.px4.io , this fixed my problem.

Great. That's the HTML version that goes to github pages - it is generated by Jenkins from ttps://github.com/PX4/Devguide with subfolders for branches. We're still working on how to handle redirect for the content in the base of the tree, which is why all that content is there still.

**Comment by hamishwillee** [comment]
It might not perfectly fix your problems, because the links in the selector are hard coded at build time. If not let me know and I'll see if relative links work in the selector.

**Comment by bys1123** [comment]
@hamishwillee Thanks for reminding me. I think this problem could use Nginx's `sub_filter` module easy to fix. I'll let you know if I had a real problem. ^_^
