### ISSUE TITLE
PX4 setup script is missing some things

### ISSUE THREAD

**Issue by lovettchris** [PX4/PX4-Devguide#691]
The `ubuntu_sim_nuttx.sh` script has this handy list of stuff:
```
# NuttX
sudo apt-get install python-serial openocd \
    flex bison libncurses5-dev autoconf texinfo \
    libftdi-dev libtool zlib1g-dev -y
```

but it is missing "genromfs" and python-jinja2, and the pip packages "empy", "jinja2", "numpy" and "toml".

**Comment by hamishwillee** [comment]
Each of the scripts builds on a common set of dependencies by importing other scripts - this makes it easier to keep things in-sync. IN this case those dependencies are in [ubuntu_sim_common_deps.sh](http://dev.px4.io/en/setup/dev_env_linux_ubuntu.html#convenience-bash-scripts).

At some point we hope to use common scripts for both end users and docker, which will make this work even more cleanly.
