### ISSUE TITLE
.txt extension Common Documentation is not in Crowdin

### ISSUE THREAD

**Issue by bys1123** [PX4/PX4-Devguide#700]
Such as `_gcc_toolchain_installation.txt` and `_ninja_build_system.txt` is not in crowdin.

Is that possible change the extension from .txt to .md.
and use `{% include "[common-docs].md" %}` in pages.

or change crowdin config file:
`source: /en/**/*[.md, .txt]`

**Comment by hamishwillee** [comment]
Thanks for pointing this out. Fixed (added another source for .txt files).

**Comment by bys1123** [comment]
@hamishwillee 
Thanks.
But, If use .txt extension, Crowdin can't handle their markdown tags. 
I saw gitbook documentation said it could use .md extension.
https://toolchain.gitbook.com/templating/conrefs.html
