### ISSUE TITLE
Simulation port numbers are incorrect

### ISSUE THREAD

**Issue by kaklik** [PX4/PX4-Devguide#701]
I want to tunnel QGC control ports to the simulation server, but I get stuck on port numbers selection. 

It is because of the [documentation](https://dev.px4.io/en/simulation/#default-px4-mavlink-udp-ports) claims the QGC listens on port 14550. It is correct because tunneling this port allows connection from PX4 to QGC.  But also the documentation mention the PX4 listens on port 14556, which is probably not correct, because of the tunneling this port to the PX4 does not allow QGC talk to PX4.
I have tried to scan listening ports on PX4 and there are no 14556 port open. Instead of this, there are few other documentation unmentioned ports opened (14570 and 14580). 

    kaklik@TF-R1:~$ ss -upnl4
    State Recv-Q Send-Q    Local Address:Port    Peer Address:Port                                       
    UNCONN0      0               0.0.0.0:14570        0.0.0.0:*     users:(("px4",pid=15118,fd=9))       
    UNCONN0      0               0.0.0.0:14580        0.0.0.0:*     users:(("px4",pid=15118,fd=10))      
    UNCONN0      0               0.0.0.0:11317        0.0.0.0:*     users:(("gzclient",pid=15116,fd=21)) 
    UNCONN0      0               0.0.0.0:11317        0.0.0.0:*     users:(("gzserver",pid=15089,fd=28)) 
    UNCONN0      0               0.0.0.0:11318        0.0.0.0:*     users:(("gzclient",pid=15116,fd=22)) 
    UNCONN0      0               0.0.0.0:11318        0.0.0.0:*     users:(("gzserver",pid=15089,fd=29)) 
    UNCONN0      0         127.0.0.53%lo:53           0.0.0.0:*                                          
    UNCONN0      0               0.0.0.0:68           0.0.0.0:*                                          
    UNCONN0      0               0.0.0.0:631          0.0.0.0:*                                          
    UNCONN0      0               0.0.0.0:33445        0.0.0.0:*                                          
    UNCONN0      0               0.0.0.0:5353         0.0.0.0:*                                          
    kaklik@TF-R1:~$ 

Above list corresponds to "gazebo_rover" simulation.

**Comment by hamishwillee** [comment]
@kaklik To the best of my knowledge the documentation is correct. PX4 sets up two ports - a remote port on 14550 and a local/network port on 14556. The default network port is set [here](https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L265). There is some doc on the [mavlink module here](https://dev.px4.io/en/middleware/modules_communication.html#mavlink_usage)

I don't have enough knowledge to comment on why this might differ from your measurements.

@bkueng Can you comment on this? 




is correct to my best understanding.

**Comment by bkueng** [comment]
@kaklik you're right, the port got changed from 14556 to 14570, to allow for multiple instances.

**Comment by kaklik** [comment]
> @kaklik you're right, the port got changed from 14556 to 14570, to allow for multiple instances.

Ok, I do not understand how changing the port number influenced the possibility to run multiple instances, but it should be documented correctly. 

@hamishwillee  Has correct note and finds documented port number in the source code, but I do not know why this port number is not used in my case.

**Comment by hamishwillee** [comment]
> Ok, I do not understand how changing the port number influenced the possibility to run multiple instances, but it should be documented correctly.

I'd guess that the scripts that support multiple instances iterate the port number for each instance - using 14556 as starting point you'd quickly clash with other allocated ports.

Yes, I'm fixing it thanks. Please review/see discussion in #710

**Comment by bkueng** [comment]
> I'd guess that the scripts that support multiple instances iterate the port number for each instance - using 14556 as starting point you'd quickly clash with other allocated ports.

Right. Simply practical reasons.
