### ISSUE TITLE
Fast RTPS installation - update to 1.7

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-Devguide#720]
FastRTPS version updated to 1.7.0 - e.g. in https://github.com/PX4/containers/issues/154

We need to update docs and scripts. E.g.
- [ ] - [Fast RTPS installation · PX4 Developer Guide](https://dev.px4.io/en/setup/fast-rtps-installation.html)
- [ ] - [Build scripts](https://github.com/PX4/Devguide/tree/master/build_scripts). I could in theory update the numbers everywhere, but I have no idea how to validate that it all is working other than "no build fails".

**Comment by hamishwillee** [comment]
Nuno, assigned to you. We can discuss if you wish.

**Comment by TSC21** [comment]
This is just the ROS2 Crystal container. Not all containers...

**Comment by TSC21** [comment]
There were several updates on the build scripts for `px4_ros_com` and some of its infrastructure. Those are relevant to update at this stage. I will do that this weekend.

**Comment by hamishwillee** [comment]
Thank you.

**Comment by TSC21** [comment]
@hamishwillee there's an [undergoing restructure of `px4_ros_com`](https://github.com/PX4/px4_ros_com/tree/ros2_package_reorganization) which will result in some changes as well on the documentation. I soon as I finish this restructuring I will move into updating the docs as well.

**Comment by hamishwillee** [comment]
Closing. This update since done, and more.
