### ISSUE TITLE
Doc Bug: jMAVSim Simulation · PX4 Developer Guide

### ISSUE THREAD

**Issue by Desync-o-tron** [PX4/PX4-Devguide#732]
DESCRIBE PROBLEM WITH DOCS HERE

"The root file system (the equivalent of / as seen by the) is located inside the build directory: "

as seen by the what?

Bug Page: [jMAVSim Simulation · PX4 Developer Guide](https://dev.px4.io/en/simulation/jmavsim.html)

**Comment by hamishwillee** [comment]
Thanks very much. Not sure what was originally intended but have created #734 to fix.
