### ISSUE TITLE
Doc Bug: Linux · PX4 Developer Guide

### ISSUE THREAD

**Issue by Desync-o-tron** [PX4/PX4-Devguide#733]
DESCRIBE PROBLEM WITH DOCS HERE

Under the Gazebo with ROS section,

I believe ubuntu_sim_ros_gazebo.sh is not entirely correctly working on ubuntu 16.04.

Line 85 uses a variable $clone_dir , which was never instantiated, causing cd to return an error.

Bug Page: [Linux · PX4 Developer Guide](https://dev.px4.io/en/setup/dev_env_linux.html#gazebo-with-ros)

**Comment by hamishwillee** [comment]
Thanks very much. Fixed in https://github.com/PX4/Devguide/commit/724083fe908b4e4d47c8f3583fc1477f9ad302a1.

This not particularly critical because at this point all the work is already done - all we're doing is returning people to the firmware tree.
