### ISSUE TITLE
Doc Bug: Controller Diagrams · PX4 Developer Guide

### ISSUE THREAD

**Issue by emialonzo** [PX4/PX4-Devguide#754]
the link https://dev.px4.io/en/tutorials/tuning_the_ecl_ekf.md is broken in https://dev.px4.io/en/flight_stack/controller_diagrams.html#multicopter-position-controller

Bug Page: [Controller Diagrams · PX4 Developer Guide](https://dev.px4.io/en/flight_stack/controller_diagrams.html)

**Comment by hamishwillee** [comment]
Thank you very much. Fixed by https://github.com/PX4/Devguide/commit/d687228db8c541b7e5466f4b8257afa1a9f43e7d
