### ISSUE TITLE
Doc Bugv1.8.2: Jenkins Continuous Integration · PX4 v1.8.2 Developer Guide

### ISSUE THREAD

**Issue by oneWayOut** [PX4/PX4-Devguide#767]
Bug Page: [Jenkins Continuous Integration · PX4 v1.8.2 Developer Guide](https://dev.px4.io/en/test_and_ci/jenkins_ci.html)

The links of [run_container.bash](https://github.com/PX4/Firmware/blob/master/integrationtests/run_container.bash) and  [run_tests.bash](https://github.com/PX4/Firmware/blob/master/integrationtests/run_tests.bash) don't exist anymore.

**Comment by hamishwillee** [comment]
Thanks @oneWayOut 

@dagar The latest docs on test execution are no longer correct: https://dev.px4.io/master/en/test_and_ci/jenkins_ci.html#test-execution

Can you clarify how this works?

Note, I have updated the old versions so they point to master branch. So in future we just need to keep master up to date.

**Comment by hamishwillee** [comment]
Issue moved to user guide: https://github.com/PX4/PX4-user_guide/issues/1019
