### ISSUE TITLE
Outdated sitl launch commands

### ISSUE THREAD

**Issue by thomasgubler** [PX4/PX4-Devguide#771]
Here and on other pages  `make posix_sitl_default gazebo` instead of ` make px4_sitl_default gazebo` (or similar) is listed as the command to run sitl.

Bug Page: [Gazebo Simulation · PX4 v1.8.2 Developer Guide](https://dev.px4.io/en/simulation/gazebo.html)

**Comment by hamishwillee** [comment]
@thomasgubler I _think_ this is "not a defect". My recollection is that the changes you mentioning went in after 1.8.2 (ie master). 

You can reopen if I am wrong, but given the  old versions of the commands do work for 1.8.2 it probably wouldn't be worth the time to go through and fix all these up.
