### ISSUE TITLE
ERROR:   [MODE: Unsupported FCU]

### ISSUE THREAD

**Issue by MOMOHTT** [PX4/PX4-Devguide#801]
Dear professor：
    I want to launch multi-vehicle simulation in Gazebo， and control the vehicles with MAVROS. I follow the guide (https://github.com/PX4/Devguide/blob/master/en/simulation/multi-vehicle-simulation.md)step by step, and pub the topic "uav0/mavros/setpoint_position/local" to change the uav0's position.  But the uav0 change nothing and the terminal display the error "MODE: Unsupported FCU". how can i solve the problem? Think you !

**Comment by MOMOHTT** [comment]
I have solved the problem. In  source code multi_uav_mavros_sitl.launch , there is a problem, the code  "<arg name="tgt_system" value="$(eval 0 + arg('ID'))"/>" should be changed to " <arg name="tgt_system" value="$(eval 1 + arg('ID'))"/>".

**Comment by hamishwillee** [comment]
Thanks very much. Can you please raise this as a code issue in https://github.com/PX4/Firmware/issues ?

It isn't a document issue, so I will close this.
