### ISSUE TITLE
Doc Bug: Arch Linux · PX4 v1.9.0 Developer Guide

### ISSUE THREAD

**Issue by yuhaim** [PX4/PX4-Devguide#820]
As described in https://github.com/PX4/Firmware/issues/11160
Should add 'ant' installation in this stage

# Common dependencies for all targets
sudo pacman -Sy --noconfirm \
    base-devel make cmake ccache git \
    ninja python-pip tar unzip zip vim wget

Bug Page: [Arch Linux · PX4 v1.9.0 Developer Guide](https://dev.px4.io/en/setup/dev_env_linux_arch.html)

**Comment by hamishwillee** [comment]
So is this just a matter of appending "ant" after wget? - ie
```
# Common dependencies for all targets
sudo pacman -Sy --noconfirm \
    base-devel make cmake ccache git \
    ninja python-pip tar unzip zip vim wget
```

**Comment by yuhaim** [comment]
Yes, I fixed this issue in manjaro by installing 'ant'
