### ISSUE TITLE
Describe how unit tests can be added

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-Devguide#827]
Now that we have support for gtest in Firmware we should document how to add these.

FYI @MaEtUgR.

**Comment by hamishwillee** [comment]
Yes. This should be an update to https://dev.px4.io/en/test_and_ci/unit_tests.html

**Comment by hamishwillee** [comment]
This was done by @jkflying . Closing!

**Comment by MaEtUgR** [comment]
Thanks @jkflying !! Reference: https://github.com/PX4/Devguide/pull/849
