### ISSUE TITLE
Param Tuning Channels gone after reboot

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [PX4/PX4-Devguide#834]
I've set up params tuning channels but they are gone after reboot.

Firmware ver: 1.9.1
Hardware: Pixhawk 4

**Comment by hamishwillee** [comment]
Closing - this is the issue tracker for bugs in docs. Suggest you post in discussion boards, first. This is likely a bug, so you should then be directed to post in PX4/Firmware.

**Comment by AlexandreBorowczyk** [comment]
oups my bad
