### ISSUE TITLE
No documentation on how px4 main processor and IO processor works 

### ISSUE THREAD

**Issue by echoGee** [PX4/PX4-Devguide#839]
An outline like this image, for example, seems to be an important information to have for the split up of tasks. 
![image](https://user-images.githubusercontent.com/518314/61338511-e2833d80-a807-11e9-9da0-374e1ea0d66a.png)

This doesn't seem to be in the docs

**Comment by hamishwillee** [comment]
@echoGee Yes it does. You will find that the hardware section on the devguide is fairly "thin": http://dev.px4.io/master/en/hardware/

This should not be unexpected - the people who have the expertise to write it or use it is a fairly small number. Which is no to say that we don't want it or welcome it.

Where would you put this? What else would you include?

@david_s5 @dagar @bkueng Is this correct, complete, sufficient? Do you have an opinion on where this could be placed to be most useful. My thinking is possibly somewhere in http://dev.px4.io/master/en/debug/reference-design.html

**Comment by bkueng** [comment]
Yes this is helpful and can go under http://dev.px4.io/master/en/debug/reference-design.html (and mention which HW has an IO). I'd add that the link between the 2 is an UART.
