### ISSUE TITLE
subscribing to multiple range sensors attached to iris model for test in sitl_gazebo

### ISSUE THREAD

**Issue by bluespirit2** [PX4/PX4-Devguide#850]
Hi
I want to know how to subscribe to two or more distance sensors oriented in different directions on iris model in sitl_gazebo. Currently, I can get distance information form distance sensor Ided as 0. The rest do not display infos as i tried through "rostopic echo mavros/distance_sensor/<sensor_name>". Thanks in advance

**Comment by hamishwillee** [comment]
Closing - this area is for docs bugs. Suggest you post request in discussion boards: https://discuss.px4.io/

**Comment by bluespirit2** [comment]
oh!ok, thanks
