### ISSUE TITLE
Toolchain build scripts highly inconsistent and failing!!

### ISSUE THREAD

**Issue by plodes** [PX4/PX4-Devguide#872]
Hello together,

I just realized that there might be a massively annoying bug in the toolchain build scripts for Linux OS. The documentation pages here: https://dev.px4.io/v1.9.0/en/setup/dev_env_linux.html, and here: https://dev.px4.io/v1.9.0/en/setup/dev_env_linux_ubuntu.html#convenience-bash-scripts are inconsistent with the acutal contents of the scripts, so you run into errors while executing.

Note: I wanted to install the toolchain for nuttx so "source ubuntu_sim_nuttx.sh"
Before I explain, let me emphasize once again that the scripts are chained to each other i.e. executing ubuntu_sim_nuttx.sh, this will include the script ubuntu_sim.sh (via wget) which again includes ubuntu_sim_common_deps.sh (via wget). 

Firstly, the link ubuntu_sim_nuttx.sh is referring to with its wget command to include the ubuntu_sim.sh doesn't exist at all. It refers to https://raw.githubusercontent.com/PX4/Devguide/master/build_scripts/ubuntu_sim.sh which gives 'Not Found 404'. Accessing ubuntu_sim.sh from the docu page you land at the link (https://raw.githubusercontent.com/PX4/Devguide/v1.9.0/build_scripts/ubuntu_sim.sh). So either this should be filled into the ubuntu_sim_nuttx.sh instead, or there should be something placed at the first link of course. 

Secondly, though the link  ubuntu_sim.sh is referring to with wget to include the ubuntu_sim_common_deps.sh does exist at ( https://raw.githubusercontent.com/PX4/Devguide/master/build_scripts/ubuntu_sim_common_deps.sh ), it has some mistakes. The block which makes the directory ~/src/Firmware is missing in this script. But it is present in the version at link https://raw.githubusercontent.com/PX4/Devguide/v1.9.0/build_scripts/ubuntu_sim_common_deps.sh.

Of course, in the other scripts references and accesses to ~/src/Firmware through errors. 

Now maybe someone decided to make changes so that the ~/src/Firmwares directory is not necessary anymore but then this should be changed in a way that everything is consistent e.g. adapting links in the documentation pages. 

I think changing the links for the wget commands within the build_scripts to the https://raw.githubusercontent.com/PX4/Devguide/v1.9.0/build_scripts/ should be sufficient, this is the directory which is also the href of the links in the documentation pages. Or if that is not intended than ALL of the scripts should be changed so that latterly executed scripts are not relying on the ~/src/Firmware directory anymore.

I think this is especially important because the whole point of these scripts is to not bother with how the toolchain is installed and how this whole execution stack works, namely "convenience" script. This goal is missed when there is additional debugging necessary. 

Peace

**Comment by hamishwillee** [comment]
Thanks for your fix! FWIW this resulted from removal of head revision files in master due to use of new script. I updated the docs to point to v1.9 versions, but did not consider that these also linked to master.
