### ISSUE TITLE
Px4 code development

### ISSUE THREAD

**Issue by avigo1999** [PX4/PX4-Devguide#880]
Hello everyone, I am actually trying develop px4 code for a model which is not present in the list of airframes in Qgroundcontrol. Can  anyone walk me through the path to develop the code and incorporate it in Qgroundcontrol such that it can be uploaded to my actual model.

**Comment by mrpollo** [comment]
Hey @avigo1999 thanks for trying PX4, you might have better luck [asking on our forums](https://discuss.px4.io). **This is the issue tracker for our documentation.**

If you are sure the airframe isn't listed on the [list of available airframes](https://dev.px4.io/master/en/airframes/airframe_reference.html), you can follow the [Adding a new Airframe guide](https://dev.px4.io/master/en/airframes/adding_a_new_frame.html).
