### ISSUE TITLE
How to install ROS,GAZEBO and PX4 in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by sagardalai** [PX4/PX4-Devguide#883]
Hello,

Please guide me to install  ROS , gazebo and px4 in ubuntu 16.04 LTS . the given script in the site is for melodic.
so how can i do this in kinetic version.

Please do provide the help.

Thank you.

**Comment by TSC21** [comment]
@sagardalai on the script, just replace the references to `melodic` by `kinetic` and you have what you need. Closing.
