### ISSUE TITLE
unable to arm my iris quadrotor 

### ISSUE THREAD

**Issue by sagardalai** [PX4/PX4-Devguide#885]
hello,

When i try to **offboard** the mode I am  unable to do as mentioned below :

pxh> commander [ INFO] [1573446629.293678636, 78427.922000000]: HP: requesting home position
pxh> **commander mode offboard**
ERROR [commander] mode change failed
pxh> [ INFO] [1573446639.304087832, 78437.922000000]: HP: requesting home position

**And also other commands:**

[ WARN] [1573446278.941455563, 78077.930000000]: GP: No GPS fix
pxh> **commander arm**
ERROR [commander] arming failed
pxh> [ INFO] [1573446288.943365602, 78087.922000000]: HP: requesting home position

**Comment by hamishwillee** [comment]
This is not a docs error. Closing.

Please raise in the discussion forums: https://discuss.px4.io/

Essentially you have to have a location - either from GPS or a local co-ordinate system. Otherwise you can't arm.
