### ISSUE TITLE
Add description about SYS_MC_EST_GROUP in optical flow setup description

### ISSUE THREAD

**Issue by pchatrath** [PX4/PX4-Devguide#9]
In http://dev.px4.io/flow_lidar_setup.html or Devguide/flow_lidar_setup.md there is description about using locap position estimator. Hoever untill SYS_MC_EST_GROUP parameter is set to lpe all the lpe parameters mentioned in the documentation won't be visible. So I think _setting  SYS_MC_EST_GROUP parameter to appropriate setting and doing a reboot_ should be added to the documentation.

**Comment by bkueng** [comment]
done!
