### ISSUE TITLE
Doc Bug: Ubuntu/Debian Linux · PX4 Developer Guide

### ISSUE THREAD

**Issue by be-nice-do-better** [PX4/PX4-Devguide#917]
when running step 2:
_source ubuntu.sh_

got warnings and errors:
![image](https://user-images.githubusercontent.com/12386794/72147364-395a8000-3403-11ea-85cd-572ee25b1af7.png)
![image](https://user-images.githubusercontent.com/12386794/72147448-67d85b00-3403-11ea-9018-13a719da34a3.png)
![image](https://user-images.githubusercontent.com/12386794/72147503-86d6ed00-3403-11ea-9e60-b29d7c19d683.png)

my system:
A new installed Ubuntu 16.04.6 LTS in Oracle VM VirtualBox

Bug Page: [Ubuntu/Debian Linux · PX4 Developer Guide](https://dev.px4.io/master/en/setup/dev_env_linux_ubuntu.html)

**Comment by hamishwillee** [comment]
@julianoes I can reproduce the above errors on Ubuntu 16.04 and Ubuntu 18.04. For Ubuntu 18.04 the build still seems to "work" (ie `HEADLESS=1 make posix jmavsim` launches simulator). @wujoho Did the above command work after your installation finished on Ubuntu 16.04?

Julian, any ideas?

**Comment by be-nice-do-better** [comment]
@hamishwillee No, both commands `make px4_sitl jmavsim` or `HEADLESS=1 make posix jmavsim` failed in my Ubuntu 16.04, as below:
![image](https://user-images.githubusercontent.com/12386794/72234929-5033e900-3634-11ea-8bed-f3dce64e92fb.png)
![image](https://user-images.githubusercontent.com/12386794/72234933-54f89d00-3634-11ea-8f33-d698e10bc074.png)

**Comment by julianoes** [comment]
Thanks for the issue @wujoho. This looks indeed broken. I'll look into it.
