### ISSUE TITLE
Doc Bug: Adding a New Airframe · PX4 v1.9.0 Developer Guide

### ISSUE THREAD

**Issue by kaklik** [PX4/PX4-Devguide#924]
In Update QGroundControl section there seems to be a wrong link to qgcresources.qrc to add a reference to the SVG image of a new group. 

Instead of this, the proper file seems to be https://github.com/mavlink/qgroundcontrol/blob/master/qgcimages.qrc

Bug Page: [Adding a New Airframe · PX4 v1.9.0 Developer Guide](https://dev.px4.io/v1.9.0/en/airframes/adding_a_new_frame.html)

**Comment by hamishwillee** [comment]
Thanks. The file moved in QGC. I've updated the branch.
