### ISSUE TITLE
Sidebar links lost

### ISSUE THREAD

**Issue by mhkabir** [PX4/PX4-Devguide#96]
Looks like the timesync and vision pages got lost due to force push or something.

**Comment by hamishwillee** [comment]
Hi @mhkabir 

Are these still gone? Can you remember what the name of the file or the heading was? I rebuilt the January version and it is not obvious which pages you might be refering to.

**Comment by hamishwillee** [comment]
@mhkabir ? See question above. Or can this be closed?

**Comment by mhkabir** [comment]
Whoops missed your comment. The timesync page is still missing. Let me find it.

**Comment by mhkabir** [comment]
It doesn't seem to be in the repo anymore; It potentially got lost during the switch to GitBook when the older repo was renamed and eventually deleted.

**Comment by hamishwillee** [comment]
@mhkabir  Is it something that could be recovered from here: http://dev.px4.io.s3-website-us-east-1.amazonaws.com/advanced-camera-trigger.html ? If so, which doc(s)

**Comment by hamishwillee** [comment]
@mhkabir I'm closing as even if these existed once, I presume they would be too out of date to be of any use now. Also I can't find them :-0
