### ISSUE TITLE
State estimator page out of date

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-Devguide#961]
The page about the state estimators is outdated:
https://dev.px4.io/master/en/advanced/switching_state_estimators.html

As far as I know inav has been removed and is no longer an option.

**Comment by hamishwillee** [comment]
Thanks @julianoes - definitely removed or "as far as you know"? If the later, who could confirm?

**Comment by bkueng** [comment]
Definitely removed. And LPE is marked as unsupported.

**Comment by hamishwillee** [comment]
Thanks guys. Fixed. @julianoes of course you should feel free to just make these changes yourself.
